project/core/views.py
"""
.. topic:: Core (views)

    Este é o módulo inicial do sistema.

    Apresenta as telas de início, direcionando para as principais funções do sistema.

.. topic:: Ações relacionadas ao módulo

    * Tela inicial: index

"""

# core/views.py

from flask import render_template, Blueprint, url_for, flash, redirect, request
from project import db, app

from project.models import tr_entregas_grupos
from project.core.forms import GrupoForm_1, GrupoForm_2

from datetime import datetime as dt


core = Blueprint("core",__name__)

@core.route('/')
def index():
    """
    +---------------------------------------------------------------------------------------+
    |Ações quando o aplicativo é colocado no ar.                                            |
    +---------------------------------------------------------------------------------------+
    """
  
        
    return render_template ('index.html') 

@core.route('/inicio')
def inicio():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta a tela inicial do aplicativo.                                                |
    +---------------------------------------------------------------------------------------+
    """

    return render_template ('index.html')    

@core.route('/entregas_grupos', methods=['GET','POST'])
def entregas_grupos():
    """
    +---------------------------------------------------------------------------------------+
    |Definição de grupos para classificar entregas.                                         |
    +---------------------------------------------------------------------------------------+
    """

    grupos = db.session.query(tr_entregas_grupos)\
                        .order_by(tr_entregas_grupos.nome)\
                        .all()

    quantidade = len(grupos)
        
    form_1 = GrupoForm_1()
    form_2 = GrupoForm_2()
    
    if form_1.submit_1.name in request.form and form_1.validate_on_submit():
        
        novo_grupo = tr_entregas_grupos(nome = form_1.nome.data, 
                                        desc = form_1.desc.data,
                                        palavras_chave= form_1.palavras_chave.data) 
        
        db.session.add(novo_grupo)
        db.session.commit()

        flash ('Grupo inserido!','sucesso')
        
        return redirect (url_for("core.entregas_grupos")) 
    
    elif form_2.submit_2.name in request.form and form_2.validate_on_submit():

        grupo = db.session.query(tr_entregas_grupos)\
                            .filter_by(id = int(form_2.id_grupo.data))\
                            .first()
                        
        grupo.nome = form_2.nome.data
        grupo.desc = form_2.desc.data
        grupo.palavras_chave= form_2.palavras_chave.data
        
        db.session.commit()

        flash ('Grupo alterado!','sucesso')
        
        return redirect (url_for("core.entregas_grupos"))

    return render_template('entregas_grupos.html', grupos = grupos, quantidade=quantidade, form_1 = form_1, form_2 = form_2)

@core.route('/<grupo_id>/deleta_grupo', methods=['GET','POST'])
def deleta_grupo(grupo_id):
    """
    +---------------------------------------------------------------------------------------+
    |Deleta grupo.                                                                          |
    +---------------------------------------------------------------------------------------+
    """
    
    tr_entregas_grupos.query.filter_by(id = grupo_id).delete()
    
    db.session.commit()
        
    flash ('Grupo deletado!','sucesso')
    
    return redirect (url_for("core.entregas_grupos"))        

project/templates/atualiza_grupo.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Grupos de Entregas</span></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Atualiza Grupo</span></li>
    </ul>
  </div>
</div>

<div class="container">
  
  <h4>Grupos de Entregas</h4>
  <div class="row">
    <div class="col">
    </div>
    <div class="col">
    </div>
    <div class="col">

      <!-- Um botão para incluir grupo  -->

      <button type="button" class="br-button secondary mr-3" data-bs-toggle='modal' data-bs-target='#inc_grupo_modal'>
              <i class="fa fa-plus" aria-hidden="true"></i>Criar Grupo
      </button> 

        {# modal inclusão de grupo de entrega #}
        <div class="modal fade" tabindex="-1" role="dialog" id="inc_grupo_modal">
          <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">Criando um Grupo</b>
                </h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">

                {% macro render_field(field,obr) %}
                  {% if obr == True %}
                    <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
                  {% else %}
                    <dt>{{ field.label(class="form-control-label") }}
                  {% endif %}
                  <dd>{{ field(**kwargs)|safe }}
                  {% if field.errors %}
                    <ul class=errors>
                    {% for error in field.errors %}
                      <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
                    {% endfor %}
                    </ul>
                  {% endif %}
                  </dd>
                {% endmacro %}

                <form class="form-group" method='POST'>

                  {{ form.hidden_tag() }}

                      <div class="row justify-content-md-center">
                        <div class="col-8 text-center">
                          {{ render_field(form.nome,class="form-control",obr=True) }}
                        </div>  
                        <div class="col-8 text-center">
                          {{ render_field(form.desc,class="form-control",obr=True) }}
                        </div> 
                        <div class="col-8 text-center">
                          {{ render_field(form.palavras_chave,class="form-control", placeholder="Separe as palavras com , (vírgula).",obr=True) }}
                        </div> 
                      </div>

                    <br>

                    <div class="form-group" align="center">
                      {{ form.submit(class="br-button primary mr-3") }} <br> <span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
                    </div>
                  
                </form>  

              </div>
              <div class="modal-footer">
              </div>
            </div>
          </div>
        </div>

    </div>
  </div>

    <br>

  {% for g in grupos %}

    <div class="card card border-secondary">
      
      <div class="card-header">
        <div class="row justify-content-between">
          <div class="col-10">
            Entrega: <b>{{g.nome}}</b>
          </div>
          <div class="col-2 text-right">

            <!-- Um botão para alterar grupo  -->

          <button type="button" class="br-button secondary mr-3" data-bs-toggle='modal' data-bs-target='#alt_grupo_modal{{grupos.index(g) + 1}}'>
                  Alterar
          </button> 

          <b>{{grupos.index(g) + 1}}</b>

            {# modal para alterar grupo de entrega #}
            <div class="modal fade" tabindex="-1" role="dialog" id="alt_grupo_modal{{grupos.index(g) + 1}}">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title">Criando um Grupo</b>
                    </h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">

                    {% macro render_field(field,obr) %}
                      {% if obr == True %}
                        <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
                      {% else %}
                        <dt>{{ field.label(class="form-control-label") }}
                      {% endif %}
                      <dd>{{ field(**kwargs)|safe }}
                      {% if field.errors %}
                        <ul class=errors>
                        {% for error in field.errors %}
                          <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
                        {% endfor %}
                        </ul>
                      {% endif %}
                      </dd>
                    {% endmacro %}

                    <form class="form-group" method='POST'>

                      {{ form.hidden_tag() }}

                          <div class="row justify-content-md-center">
                            <div class="col-8 text-center">
                              {{ render_field(form.nome,class="form-control",obr=True) }}
                            </div>  
                            <div class="col-8 text-center">
                              {{ render_field(form.desc,class="form-control",obr=True) }}
                            </div> 
                            <div class="col-8 text-center">
                              {{ render_field(form.palavras_chave,class="form-control", placeholder="Separe as palavras com , (vírgula).",obr=True) }}
                            </div> 
                          </div>

                        <br>

                        <div class="form-group" align="center">
                          {{ form.submit(class="br-button primary mr-3") }} <br> <span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
                        </div>
                      
                    </form>  

                  </div>
                  <div class="modal-footer">
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
        <div class="row">
          <div class="col">
            Descrição: <b>{{g.desc}}</b>
          </div>
        </div>
      </div>

      <div class="card-body">

        <div class="row justify-content-center">
          <div class="col-10 text-center">
            Palavras_chave: <b>{{ g.palavras_chave }} </b>
          </div>
        </div>

      </div>

             
    </div>

  {% endfor %}


</div>
{% endblock %}

project/templates/card_menu.html
<div class="card mx-3 mb-3 flex-fill col-md-3">
  <div class="card-body text-center card-box position-relative">
    <a href="{{link}}">
      <i class="fa-solid {{icon}}"></i>
      <h4 class="card-title mt-3">{{title}}</h4>
    </a>
    <button tabindex="0" class="btn rounded-circle btn-help" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-title="{{title}}" data-bs-content="{{description}}"><i class="fa-solid fa-info"></i></button>
  </div>
</div>

project/templates/entregas_grupos.html
{% extends "template_gov.html" %}
{% block content %}

<style>
  .hidden-field-container {
      display: none; /* Hides the element and removes it from layout flow */
      /* or */
      visibility: hidden; /* Hides the element but reserves its space in the layout */
  }
</style>

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Grupos de Entregas</span>
      </li>
    </ul>
  </div>
</div>

<div class="container">
  
  <h4>Grupos de Entregas</h4>
  <div class="row">
    <div class="col">
    </div>
    <div class="col">
    </div>
    <div class="col">

      <!-- Um botão para incluir grupo  -->

      <button type="button" class="br-button secondary mr-3" data-bs-toggle='modal' data-bs-target='#inc_grupo_modal'>
              <i class="fa fa-plus" aria-hidden="true"></i>Criar Grupo
      </button> 

        {# modal inclusão de grupo de entrega #}
        <div class="modal fade" tabindex="-1" role="dialog" id="inc_grupo_modal">
          <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">Criando um Grupo</b>
                </h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">

                {% macro render_field(field,obr) %}
                  {% if obr == True %}
                    <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
                  {% else %}
                    <dt>{{ field.label(class="form-control-label") }}
                  {% endif %}
                  <dd>{{ field(**kwargs)|safe }}
                  {% if field.errors %}
                    <ul class=errors>
                    {% for error in field.errors %}
                      <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
                    {% endfor %}
                    </ul>
                  {% endif %}
                  </dd>
                {% endmacro %}

                <form class="form-group" method='POST'>

                  {{ form_1.hidden_tag() }}

                      <div class="row justify-content-md-center">
                        <div class="col-8 text-center">
                          {{ render_field(form_1.nome,class="form-control",obr=True) }}
                        </div>  
                        <div class="col-8 text-center">
                          {{ render_field(form_1.desc,class="form-control",obr=True) }}
                        </div> 
                        <div class="col-8 text-center">
                          {{ render_field(form_1.palavras_chave,class="form-control", placeholder="Separe as palavras com , (vírgula).",obr=True) }}
                        </div> 
                      </div>

                    <br>

                    <div class="form-group" align="center">
                      {{ form_1.submit_1(class="br-button primary mr-3") }} <br> <span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
                    </div>
                  
                </form>  

              </div>
              <div class="modal-footer">
              </div>
            </div>
          </div>
        </div>

    </div>
  </div>

    <br>

  {% for g in grupos %}

    <div class="card card border-secondary">
      
      <div class="card-header">
        <div class="row justify-content-between">
          <div class="col-8">
            Entrega: <b>{{g.nome}}</b>
          </div>
          <div class="col-4 text-right">

            <!-- Um botão para alterar grupo  -->

            <button type="button" class="br-button secondary mr-3" data-bs-toggle='modal' data-bs-target='#alt_grupo_modal{{grupos.index(g) + 1}}'>
                    Alterar
            </button> 

            <abbr title="ATENÇÃO!! AO CLICAR NESTE BOTÃO, O GRUPO SERÁ DELETADO!">
              <button type="button" class="br-button circle secondary mr-3" data-bs-toggle='modal' data-bs-target='#del_modal_{{grupos.index(g) + 1}}'>
                <i class="fas fa-times" aria-hidden="true"></i></button>
            </abbr>

            <b>{{grupos.index(g) + 1}}</b>

            {# modal para alterar grupo de entrega #}
            
            <div class="modal fade" tabindex="-1" role="dialog" id="alt_grupo_modal{{grupos.index(g) + 1}}">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title">Criando um Grupo</b>
                    </h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">

                    {% macro render_field_2(field,obr) %}
                      {% if obr == True %}
                        <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
                      {% else %}
                        <dt>{{ field.label(class="form-control-label") }}
                      {% endif %}
                      <dd>{{ field(**kwargs)|safe }}
                      {% if field.errors %}
                        <ul class=errors>
                        {% for error in field.errors %}
                          <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
                        {% endfor %}
                        </ul>
                      {% endif %}
                      </dd>
                    {% endmacro %}

                    <form class="form-group" method='POST'>

                      {{ form_2.hidden_tag() }}

                        <div class="hidden-field-container"> 
                          {{ form_2.id_grupo(value = g.id) }}
                        </div>   

                          <div class="row justify-content-md-center">
                            <div class="col-8 text-center">
                              {{ render_field_2(form_2.nome,class="form-control",obr=True, value = g.nome) }}
                            </div>  
                            <div class="col-8 text-center">
                              {{ render_field_2(form_2.desc,class="form-control",obr=True, value = g.desc) }}
                            </div> 
                            <div class="col-8 text-center">
                              {% set f = form_2.palavras_chave.process_data(g.palavras_chave) %}
                              {{ render_field_2(form_2.palavras_chave,class="form-control",obr=True) }}
                            </div> 
                          </div>

                        <br>

                        <div class="form-group" align="center">
                          {{ form_2.submit_2(class="br-button primary mr-3") }} <br> <span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
                        </div>
                      
                    </form>  

                  </div>
                  <div class="modal-footer">
                  </div>
                </div>
              </div>
            </div>

            {# modal deleção de Grupo #}

            <div class="modal" tabindex="-1" role="dialog" id="del_modal_{{grupos.index(g) + 1}}">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">

                        <div class="p-3 mb-2 bg-danger text-white">
                        <h4 class="modal-title">Deletar o grupo {{g.nome}}?</h4>
                        </div>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> 

                  </div>
                  <div class="modal-body">
                    <p>Deseja realmente remover o Grupo?</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>

                    <form action="{{url_for('core.deleta_grupo',grupo_id=g.id)}}" method="post">
                      <input class="btn btn-danger" type="submit" name="" value="Deletar">
                    </form>

                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>

        <div class="row">
          <div class="col">
            Descrição: <b>{{g.desc}}</b>
          </div>
        </div>
      </div>

      <div class="card-body">

        <div class="row justify-content-center">
          <div class="col-10 text-center">
            Palavras_chave: <b>{{ g.palavras_chave }} </b>
          </div>
        </div>

      </div>

             
    </div>

  {% endfor %}


</div>
{% endblock %}

project/templates/fraciona_ft_entregas.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Fraciona ft_entragas</span>
      </li>
    </ul>
  </div>
</div>

<div class="container">

<div class="jumbotron">
<h1>Escolher dimensão para ligar a ft_entregas (NÃO ALTERAR SEQUÊNCIA)</h1>

{% macro render_field(field,obr) %}
  {% if obr == True %}
    <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
  {% else %}
    <dt>{{ field.label(class="form-control-label") }}
  {% endif %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

<form class="needs-validation" method='POST' >
  {{ form.hidden_tag() }}

  <div class="form-group col-9">
    {{ render_field(form.dimensao,class="form-control") }}
  </div>

  <div class="form-group">
    {{ form.submit(class="br-button primary mr-3") }}
  </div>

</div>
</div>

{% endblock %}

project/templates/index.html
{% extends "template_gov.html" %}
{% block content %}

<div class="row mt-2">
  <div class="d-flex justify-content-center  flex-wrap">

    {% with 
      icon="fa-archive", 
      title="Carrega Stage Area",
      description="Executa a carga das tabelas stage a partira do banco de dados do Petrvs.",
      link=url_for("stage.carregaStage")
    %}
      {% include "card_menu.html" %}
    {% endwith %}

  </div>
</div>

<div class="row mt-2">
  <div class="d-flex justify-content-center  flex-wrap">

    {% with 
      icon="fa-database", 
      title="Gera Dimensões",
      description="Cria as tabelas de dimensão a partir da área de stage.",
      link=url_for("dim_fat.gera_dimensoes")
    %}
      {% include "card_menu.html" %}
    {% endwith %}

  </div>
</div>  

<div class="row mt-2">
  <div class="d-flex justify-content-center  flex-wrap">

    {#
    {% with 
      icon="fa-snowflake", 
      title="Gera ft_entregas",
      description="Gera snowflake da fato ft_entregas.",
      link=url_for("dim_fat.gera_fatos",ft="ft_entregas")
    %}
      {% include "card_menu.html" %}
    {% endwith %}
    #}

    {% with 
      icon="fa-snowflake", 
      title="Gera ft_desempenho",
      description="Gera snowflake da fato ft_desempenho.",
      link=url_for("dim_fat.gera_fatos",ft="ft_desempenho")
    %}
      {% include "card_menu.html" %}
    {% endwith %}

  </div>
</div> 

{% endblock %}